fix(manifests): switches to use patches and overlays
maistra/odh-manifests pull request #18
Opened 2023-06-19 16:51 UTC by bartoszmajsak

This PR reverts upstream settings (such as oauth-proxy container and related resources) and introduces `service-mesh` overlay which will patch manifests for service mesh instead of overwriting actual files.

Please take a note of comments - kfdef way of using kustomize is extremely buggy and certain things were not trivial to make them work :)

2023-06-20 19:56 UTC, cam-garrison reviewed
Looks great as a whole, have a few small suggestions. Was able to deploy successfully on CRC following the new markdown file.

2023-06-20 19:56 UTC, cam-garrison commented on odh-dashboard/base/role.yaml
> +  namespace: opendatahub
Same for here, if we can avoid hardcoding this ns,

2023-06-21 04:49 UTC, bartoszmajsak commented on odh-dashboard/overlays/service-mesh/kustomization.yaml
> +- smm.yaml
It's in the same folder, but there's no need for that. The same file is in `odh-common` now so it would be applied twice. Otherwise, you would get kustomize failure for missing file. Removed in c66b207

2023-06-21 04:50 UTC, bartoszmajsak commented on odh-dashboard/base/role.yaml
> +  namespace: opendatahub
Done in a224192

2023-06-21 04:50 UTC, bartoszmajsak commented on odh-common/overlays/service-mesh/smm.yaml
> +  namespace: opendatahub
Done in a224192

2023-06-21 04:53 UTC, bartoszmajsak commented on odh-dashboard/base/kustomization.yaml
> +  newTag: v4.8
```suggestion
```

2023-06-21 13:46 UTC, cam-garrison requested changes
I'm unclear on only one piece :+1:

2023-06-21 13:46 UTC, cam-garrison commented on odh-dashboard/base/kustomization.yaml
> +
Why was the image for `oauth-proxy` deleted in base/kustomization? Wouldn't this be necessary to deploy without our overlay?

2023-06-21 13:46 UTC, cam-garrison commented on odh-common/overlays/service-mesh/smm.yaml
>      namespace: istio-system
noting just for future/awareness that this `smm` is hardcoded to refer to basic SMCP

2023-06-21 15:11 UTC, bartoszmajsak commented on odh-common/overlays/service-mesh/smm.yaml
>      namespace: istio-system
Yes, it will be adjusted/templated in the plugin. Working on it. Good catch!

2023-06-21 15:17 UTC, bartoszmajsak commented on odh-dashboard/base/kustomization.yaml
> +
Good catch. I deleted it as it wasn't on the target branch (`service-mesh-integration`) but I just double checked and it is defined on `master`.

2023-06-21 15:26 UTC, cam-garrison approved these changes
LGTM!

2023-06-21 15:27 UTC, merged